### ISSUE TITLE
Could you take a picture of the size of apps with scaling off?

### ISSUE THREAD

**Issue by atomicwrites** [ManuGithubSteam/Surface3ProArch#1]
I'm considering a Surface Pro 3 and while not a deal breaker, the scaling issues seem annoying. I was wondering if using it without scaling would be feasible. Can you take a picture of a browser and maybe the activities view with no scaling, to see the size? Thanks.

**Comment by ManuGithubSteam** [comment]
Hi Aventura5,
Nice to read from you!

First i can say the SP3 is a very good machine! I like it its well made. The keyboard and touch is good and the linux support is very good. Its just those little things you have to work on.

Ok here is some info:

- With scaling you can not rotate because the rotated orientation will not honor the scaling factor.
-- However i did not try do descale, then rotate and then scale again. Maybe worth a shot.

- Scaling works very well with GTK(3). However the Stylus will not see the scaled space, just the normal one. So you cant use it to draw on the whole screen. It seems only the drawing is affected i can click on the whole screeen but not draw in QT Apps (Krita). GTK3 Apps seem to be not affected (Mypaint).

- I solved this with a scaled session for normal work and an unscaled one if i want to draw with Krita.

- If you use onle GTK apps i belive you will have no issue with the scaleing and drawing AFAIK it only affects QT apps.

I will post pics shortly mobile needs to charge....

**Comment by ManuGithubSteam** [comment]
Wit 1.25 scaling:
![img_20180214_151010](https://user-images.githubusercontent.com/3456994/36210844-cf4cc498-119f-11e8-9ba7-cdb94d06a69d.jpg)
![img_20180214_151021](https://user-images.githubusercontent.com/3456994/36210845-cf6d7378-119f-11e8-9146-af312d0d81e5.jpg)
![img_20180214_151041](https://user-images.githubusercontent.com/3456994/36210846-cf9193c0-119f-11e8-838a-eac25d345e07.jpg)

**Comment by ManuGithubSteam** [comment]
Without scaling:

![img_20180214_151232](https://user-images.githubusercontent.com/3456994/36210898-f1702db2-119f-11e8-8866-b997c366f1d5.jpg)
![img_20180214_151240](https://user-images.githubusercontent.com/3456994/36210899-f190d2ec-119f-11e8-9e44-1c98cca0e6bd.jpg)
![img_20180214_151259](https://user-images.githubusercontent.com/3456994/36210900-f1b5195e-119f-11e8-9ed3-009e2c624f36.jpg)
![img_20180214_151308](https://user-images.githubusercontent.com/3456994/36210901-f1d35676-119f-11e8-8def-d6df2143d3d2.jpg)

**Comment by ManuGithubSteam** [comment]
In general i dont see me work normal work without the scaleing the stuff is just too tiny.
But as described you can scale without issue when you not use QT Apps. And if you want to draw like me with Krita then just make a new session for it. I think that is quaite a good solution :-)

**Comment by atomicwrites** [comment]
Thanks. You're right, no scaling is pretty small. It's not a deal breaker, this is probably the only device that fits what I want. And krita would be the only thing I can think of to be affected so a new session is a usable workaround.
